# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [2]:
import numpy as np

array_2d = np.ones((5,5))*6

array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
import numpy as np

checkboard_pattern = np.ones((8,8))*3
checkboard_pattern[1::2, ::2] = 9
checkboard_pattern[::2, 1::2] = 9
checkboard_pattern

array([[3., 9., 3., 9., 3., 9., 3., 9.],
       [9., 3., 9., 3., 9., 3., 9., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.],
       [9., 3., 9., 3., 9., 3., 9., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.],
       [9., 3., 9., 3., 9., 3., 9., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.],
       [9., 3., 9., 3., 9., 3., 9., 3.]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [13]:
print(np.empty((3,4)))
print(np.ones((3,3), dtype=int)*6)

[[1.57076922e-076 4.57134226e-071 3.66118410e-086 3.35859838e-143]
 [6.01433264e+175 6.93885958e+218 5.56218858e+180 3.94356143e+180]
 [3.92587840e-033 1.48976747e+161 9.33876746e-067 3.12164925e-033]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [24]:
centigrade_deg = np.array([-17.77777778, -11.11111111, 7.33888889, 1.11111111, 37.72777778])
print(centigrade_deg)

fahren_deg = (centigrade_deg*9/5)+32
fahren_deg = np.around(fahren_deg)
print(fahren_deg)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
[ -0.  12.  45.  34. 100.]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [29]:
input_array = np.array([1.00000000+0.j, 0.70710678+0.j, 70710678j])
print(input_array.real)
print(input_array.imag)

[1.         0.70710678 0.        ]
[       0.        0. 70710678.]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [41]:
array1 = np.array([0,10,20,40,60])
array2 = np.array([0,40])

print(np.in1d(array1, array2))

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
array1 = np.array([0,10,20,40,60])
array2 = np.array([10,30,40])
lst = []
for i in range(len(array1)):
    for j in range(len(array2)):
        if array1[i] == array2[j]:
            lst.append(array1[i])
print(np.array(lst))

[10 40]


In [3]:
array1 = np.array([0,10,20,40,60])
array2 = np.array([10,30,40])

final_array = np.intersect1d(array1,array2)
final_array

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [6]:
input_array = np.array([10,10,20,20,30,30])
lst = []

for i in range(len(input_array)):
    if input_array[i] not in lst:
        lst.append(input_array[i])
print(np.array(lst))

[10 20 30]


In [5]:
print(np.unique(np.array([10,10,20,20,30,30])))

[10 20 30]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [43]:
array1 = [0,10,20,40,60,80]
array2 = [10,30,40,50,70]

print(np.setxor1d(array1,array2))

[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [69]:
array1 = np.array([10,True,20,40])
x = 0

for i in range(len(array1)):
    if array1[i] == 0 or array1[i] == False:
        x += 1
        break
        
if x == 0:
    print(True)
else:
    print(False)

True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [72]:
array1 = np.array([False,20,False,0,50])
x = 0

for i in range(len(array1)):
    if array1[i] != 0 or array1[i] != False:
        x += 1
        break
        
if x == 0:
    print(False)
else:
    print(True)

True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [9]:
array1 = np.array([1,2,3,4])

print(np.tile(array1,2))
print(np.tile(array1,3))

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [11]:
given_arr = np.array([1,2,3,4,5,6])

print(given_arr.argmax())
print(given_arr.argmin())

5
0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [15]:
a = np.array([1,2])
b = np.array([4,5])

print("checking for a>b:")
for i in range(len(a)):
    if a[i] > b[i]:
        print(True)
    else:
        print(False)
        
print("checking for a>=b:")
for i in range(len(a)):
    if a[i] >= b[i]:
        print(True)
    else:
        print(False)
        
print("checking for a<b:")
for i in range(len(a)):
    if a[i] < b[i]:
        print(True)
    else:
        print(False)
        
print("checking for a<=b:")
for i in range(len(a)):
    if a[i] <= b[i]:
        print(True)
    else:
        print(False)

checking for a>b:
False
False
checking for a>=b:
False
False
checking for a<b:
True
True
checking for a<=b:
True
True


In [18]:
a = np.array([1,2])
b = np.array([4,5])

print("a>b")
print(np.greater(a,b))

print("a>=b")
print(np.greater_equal(a,b))

print("a<b")
print(np.less(a,b))

print("a<=b")
print(np.less_equal(a,b))

a>b
[False False]
a>=b
[False False]
a<b
[ True  True]
a<=b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [53]:
given_arr = np.array([[2,5],[7,4]])

print("sort along the first axis:")
print(np.sort(given_arr, axis=0))

print("sort along the second axis:")
print(np.sort(given_arr, axis=1))

sort along the first axis:
[[2 4]
 [7 5]]
sort along the second axis:
[[2 5]
 [4 7]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [61]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
second_names = ('Woolum','Battle', 'Plotner','Brien', 'Stahl')

sort_names = np.lexsort((first_names, second_names))
print(sort_names)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [25]:
arr = np.array([[0,10,20],[20,30,40]])

print("values bigger than 10 are: ", arr[arr>10])
print("their indices are: ", np.nonzero(arr>10))

values bigger than 10 are:  [20 20 30 40]
their indices are:  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [73]:
arr = np.array([[1,2,3,4],[5,6,7,8],[2,5,7,6],[3,4,5,6]])

print(arr.itemsize)
print(arr.size)
print("memory size of array is:", (arr.itemsize*arr.size))

8
16
memory size of array is: 128


## Great Job!